config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'push_notifications#new'
  post '/send_message', to: 'push_notifications#send_message'
end

app/models/application_record.rb
# frozen_string_literal: true

# All the model are inherit from this application record.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/push_notification.rb
# frozen_string_literal: true

# Push Notification Model
class PushNotification < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# This is application controller.
# All controller inherit from this controller.
class ApplicationController < ActionController::Base
end

app/controllers/push_notifications_controller.rb
# frozen_string_literal: true

# This is for send push notification in devices.
class PushNotificationsController < ApplicationController
  def initialize
    @push_notification = PushNotification.new
  end

  def new
    @push_notification
  end

  def send_message
    @push_notification = PushNotification.new(push_notification_params)
    # device_token stored with mobile app
    # platform either android or iOS this is required due to multiple devices.
    SendMessageWorker.perform_async(platform, device_token, @push_notification
      .message)
    flash[:notice] = 'Your message was successfully scheduled and is currently
                      being delivered to its recipients.'
    redirect_to root_path
  end

  private

  def push_notification_params
    params.require(:push_notification).permit(:message)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# This is application helper for define methods
module ApplicationHelper
end

app/helpers/push_notifications_helper.rb
# frozen_string_literal: true

# Push Notification helper
module PushNotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushNotificationWithBackgroundJob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/push_notifications/_form.html.erb
<%= form_for(@push_notification, url: send_message_path) do |f| %>
  <div class="form-group">
    <%= f.label :Message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="form-group">
    <%= f.submit "Send Push Notification", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/push_notifications/new.html.erb
<div class="container">
  <h1>Send Push Notification</h1>
  <%= render 'form' %>
</div>